!
password zebra
enable password zebra
!
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 3
    no bgp network import-check
    !
    ! NEIGHBORS
    !
    neighbor 10.2.3.1 remote-as 2
    neighbor 1.1.1.1 remote-as 3
    neighbor 1.1.1.1 update-source 2.2.2.2
    neighbor 10.3.4.2 remote-as 4
    !
    ! NETWORKS
    !
    network 3.0.0.0/8
    network 10.2.3.0/30
    network 10.3.4.0/30
    !
    ! POLICIES
    ! in=annuncia, out=accetta
    neighbor 10.2.3.1 prefix-list defaultRoute in
    neighbor 10.2.3.1 prefix-list as2Out out

    neighbor 1.1.1.1 prefix-list defaultRoute in
    neighbor 1.1.1.1 prefix-list defaultRoute out

    neighbor 10.3.4.2 prefix-list defaultRoute in
    neighbor 10.3.4.2 prefix-list defaultRoute out
    !
    ip prefix-list as2Out deny 4.0.0.0/8
    ip prefix-list as2Out permit any

    ip prefix-list as4Out permit 3.0.0.0/8
    ip prefix-list as4Out permit 1.0.0.0/8
    ip prefix-list as4Out permit 10.1.3.0/30
    ip prefix-list as4Out permit 10.2.3.0/30

    ip prefix-list defaultRoute permit any
!
!
! FRRouting configuration file
!
!
!  RIP CONFIGURATION
!
router rip
network 3.0.0.0/8
    redistribute bgp
!
log file /var/log/frr/frr.log