!
password zebra
enable password zebra
!
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 1
    no bgp network import-check
    !
    ! NEIGHBORS
    !
    neighbor 1.1.1.1 remote-as 1
    neighbor 1.1.1.1 update-source 2.2.2.2
    neighbor 10.20.1.2 remote-as 2
    !
    ! NETWORKS
    !
    network 1.0.0.0/8
    network 10.20.1.0/30
    !
    ! POLICIES
    ! in=annuncia, out=accetta
    neighbor 1.1.1.1 prefix-list defaultRoute in
    neighbor 1.1.1.1 prefix-list defaultRoute out

    neighbor 10.20.1.2 prefix-list defaultRoute in
    neighbor 10.20.1.2 prefix-list defaultRoute out
    !
    ip prefix-list defaultRoute permit any
!
!
! FRRouting configuration file
!
!
!  RIP CONFIGURATION
!
router rip
!send rip multicast packets to interfaces falling into this prefix
network 1.0.0.0/8
redistribute bgp
redistribute connected
!
log file /var/log/frr/frr.log