as1r1[0]="A"
as1r1[1]="B"
as1r1[2]="C"
as1r1[image]="kathara/frr"

as2r1[0]="C"
as2r1[1]="D"
as2r1[2]="F"
as2r1[image]="kathara/frr"

as4r1[0]="F"
as4r1[1]="G"
as4r1[2]="E"
as4r1[image]="kathara/frr"

as3r1[0]="M"
as3r1[1]="H"
as3r1[2]="E"
as3r1[3]="D"
as3r1[image]="kathara/frr"

as3r2[0]="L"
as3r2[1]="H"
as3r2[image]="kathara/frr"

as3r3[0]="B"
as3r3[1]="L"
as3r3[2]="M"
as3r3[image]="kathara/frr"
