!
password zebra
enable password zebra
!
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 200
    no bgp network import-check
    !
    ! NEIGHBORS
    !
    neighbor 100.200.2.1 remote-as 100
    neighbor 3.3.3.3 remote-as 200
    neighbor 3.3.3.3 update-source 2.2.2.2
    neighbor 4.4.4.4 remote-as 200
    neighbor 4.4.4.4 update-source 2.2.2.2
    
    !
    ! NETWORKS
    !
    network 1.0.0.0/8
    network 100.200.2.0/30
    !
    ! POLICIES
    ! in=annuncia, out=accetta
    neighbor 100.200.2.1 prefix-list defaultRoute in
    neighbor 100.200.2.1 prefix-list defaultRoute out

    neighbor 3.3.3.3 prefix-list defaultRoute in
    neighbor 3.3.3.3 prefix-list defaultRoute out

    neighbor 4.4.4.4 prefix-list defaultRoute in
    neighbor 4.4.4.4 prefix-list defaultRoute out
    !
    ip prefix-list defaultRoute permit any
!
!
! FRRouting configuration file
!
!
!  OSPF CONFIGURATION
!
!
! Default cost for exiting an interface is 10
!interface eth0
!	ospf cost 10
!
router ospf
! Speak OSPF on all interfaces falling in the listed subnets
    network 1.0.0.0/8 area 0.0.0.0
    redistribute bgp
    redistribute connected
!
!
log file /var/log/frr/frr.log