!
password zebra
enable password zebra
!
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 1
    no bgp network import-check
    !
    ! NEIGHBORS
    !
    neighbor 10.1.2.2 remote-as 2
    neighbor 10.1.3.2 remote-as 3
    !
    ! NETWORKS
    !
    network 1.0.0.0/8
    network 10.1.2.0/30
    network 10.1.3.0/30
    !
    ! POLICIES
    ! in=annuncia, out=accetta
    neighbor 10.1.2.2 prefix-list defaultRoute in
    neighbor 10.1.2.2 prefix-list as2Out out

    neighbor 10.1.3.2 prefix-list defaultRoute in
    neighbor 10.1.3.2 prefix-list as4Out out
    !
    ip prefix-list as2Out permit 1.0.0.0/8
    ip prefix-list as2Out permit 10.1.2.0/30

    ip prefix-list as3Out permit 1.0.0.0/8
    ip prefix-list as3Out permit 10.1.3.0/30
    
    ip prefix-list defaultRoute permit any
!
log file /var/log/frr/frr.log
