!
password zebra
enable password zebra
!
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 4
    no bgp network import-check
    !
    ! NEIGHBORS
    !
    neighbor 10.2.4.1 remote-as 2
    neighbor 10.3.4.1 remote-as 3
    !
    ! NETWORKS
    !
    network 4.0.0.0/8
    network 10.2.4.0/30
    network 10.3.4.0/30
    !
    ! POLICIES
    ! in=annuncia, out=accetta

    neighbor 10.2.4.1 prefix-list defaultRoute in
    neighbor 10.2.4.1 prefix-list defaultRoute out

    neighbor 10.3.4.1 prefix-list defaultRoute in
    neighbor 10.3.4.1 prefix-list defaultRoute out
    !
    ip prefix-list defaultRoute permit any
!
log file /var/log/frr/frr.log
