!
password zebra
enable password zebra
!
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 2
    no bgp network import-check
    !
    ! NEIGHBORS
    !
    neighbor 10.20.1.1 remote-as 1
    neighbor 2.0.0.1 remote-as 2
    neighbor 20.30.1.2 remote-as 3
    !
    ! NETWORKS
    !
    network 2.0.0.0/8
    network 10.20.1.0/30
    network 20.30.1.0/30
    !
    ! POLICIES
    ! in=annuncia, out=accetta
    !neighbor MODIFICA default-originate !se isp upstream che segnala 0.0.0.0
    neighbor 10.20.1.1 prefix-list defaultRoute in
    neighbor 10.20.1.1 prefix-list defaultRoute out
    
    neighbor 2.0.0.1 prefix-list defaultRoute in
    neighbor 2.0.0.1 prefix-list defaultRoute out

    neighbor 20.30.1.2 prefix-list defaultRoute in
    neighbor 20.30.1.2 prefix-list defaultRoute out
    !
    ip prefix-list defaultRoute permit any
!
!
! FRRouting configuration file
!
!
!  RIP CONFIGURATION
!
router rip
!send rip multicast packets to interfaces falling into this prefix
network 2.0.0.0/8
redistribute bgp
redistribute connected
!
log file /var/log/frr/frr.log